name: Build Kernel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kernel build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            make \
            gcc \
            g++ \
            gcc-aarch64-linux-gnu \
            crossbuild-essential-arm64 \
            cpio \
            rsync \
            kmod \
            device-tree-compiler \
            lz4 \
            xz-utils \
            zstd \
            python3 \
            python3-pip \
            python3-dev \
            git \
            wget \
            curl \
            file \
            openssl \
            libncurses-dev \
            dwarves \
            perl \
            xmlto \
            docbook-utils \
            gawk \
            util-linux \
            pahole \
            linux-libc-dev \
            clang \
            llvm \
            lld \
            clang-format \
            clang-tidy \
            libclang-dev \
            llvm-dev

      - name: Run script to start building kernel
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          chmod +x scripts/kbuild.sh
          export CC=clang LD=ld.lld AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++
          ./scripts/kbuild.sh
